FROM debian:stable-slim

RUN apt-get update && \
    apt-get install -y nginx openssl && \
    rm -rf /var/lib/apt/lists/*

# Create SSL directory and generate self-signed certificate
RUN mkdir -p /etc/nginx/ssl && \
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
      -keyout /etc/nginx/ssl/jesopan-.42.fr.key \
      -out /etc/nginx/ssl/jesopan-.42.fr.crt \
      -subj "/C=/ST=/L=/O=/OU=/CN=jesopan-.42.fr"

# Copy custom Nginx config
COPY ./nginx.config /etc/nginx/conf.d/default.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]